### ISSUE TITLE
Project will not compile.

### ISSUE THREAD

**Issue by delebash** [wblong/GeoGDAL#1]
When I launch the project in 4.26 it asks to compile the plugins but fails.  I am guessing the GDAL plugin is not building.  Do I need to build Unreal GDAL using [conan-ue4cli](https://github.com/adamrehn/conan-ue4cli) per their instructions or should it compile as a normal plugin? TY

**Comment by buaaCCJ** [comment]
I got same questions too

**Comment by delebash** [comment]
I ended up building UnrealGDAL from source and it worked.  https://github.com/TensorWorks/UnrealGDAL.

**Comment by delebash** [comment]
Later I will just make a repo for binary builds of GDAL since I already have it setup.  I will post a link here when it is done.  UE 4.27 and UE5.0 preview have Georeferencing built in.  https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/Georeferencing/

**Comment by buaaCCJ** [comment]
> Later I will just make a repo for binary builds of GDAL since I already have it setup. I will post a link here when it is done. UE 4.27 and UE5.0 preview have Georeferencing built in. https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/Georeferencing/
Really thanks

**Comment by buaaCCJ** [comment]
> Later I will just make a repo for binary builds of GDAL since I already have it setup. I will post a link here when it is done. UE 4.27 and UE5.0 preview have Georeferencing built in. https://docs.unrealengine.com/4.27/en-US/BuildingWorlds/Georeferencing/

can't wait to get a release of GDAL for unreal 426,

**Comment by delebash** [comment]
Here is the 4.26 just download the repo it has the prebuilt binaries.  Let me know if you have any problems.  

https://github.com/delebash/UnrealGDAL_Binaries

**Comment by wblong** [comment]
solved!
